### ISSUE TITLE
Future of this repository

### ISSUE THREAD

**Issue by stucki** [jrizzoli/vendor_google#19]
Hi!

First of all, thanks for providing a solid gapps package. It runs really well.
I was wondering how you plan to maintain this repository in the future, because the Git history is growing rapidly because of the binary archives.

My sugggestion is to put them at a separate place for download, and have the build script fetch them from wherever that is (outside of the Git repository).

Another interesting approach is found in the Open Gapps project (https://github.com/opengapps/opengapps), who are maintaining a separate repository for binaries of each architecture. However, they are also downloading everything during build, so the result is currently the same regarding disk usage...

My wish would be that this is a really small repository with just some scripts and certificates, and everything else is downloaded during build. That should not make more than 100 MB according to the size of the builds...

**Comment by jrizzoli** [comment]
Well. If you want to have just the build system branch git clone URL -b master.
I've finally choosen the best way to release gapps. You can find 3 new branches: arm, arm64 and x86. Each one can be dloaded as zip, which is flashable. Why this? It's really easy for me to push just the changes files instead of a full zip each time. Git pull also makes me push common files only once, so it's really fast to manage. Git history will do the trick if you want an older gapps package. The build branch will be deleted soon.

**Comment by jalonsomartinez** [comment]
I have downloaded the zip for arm, from the link in cyanogenmod wiki, and it is not flashable.
Maybe it's because there is a folder it the top levee of the zip?
The link I have clicked is
https://github.com/cgapps/vendor_google/archive/arm.zip
Thanks!

**Comment by BHSPitMonkey** [comment]
Just to chime in, the typical way of hosting builds on GitHub is through the "Releases" feature. From the repository's Releases tab, you can create a release and upload one or more files ("release assets") users can download. You can also automate this by hitting the [releases API](https://developer.github.com/v3/repos/releases/).
